services:  
  server:
    image: mean-server
    ports:
      - '3000:5200'    
    depends_on:      
      - mongodb
    environment:
      ATLAS_URI: mongodb://mongodb:27017/meanStackExample?retryWrites=true&w=majority  
  mongodb:    
    image: mongodb/mongodb-community-server:5.0-ubuntu2004    
    volumes:      
      - mongo-data:/data/db
    ports:      
      - '27017:27017'
volumes:  
  mongo-data: