services:  
  mongodb:    
    image: mongodb/mongodb-community-server:5.0-ubuntu2004    
    container_name: mongo
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: test
      MONGODB_INITDB_ROOT_PASSWORD: test
    ports:      
      - '27017:27017' 
  server:
    image: mean-server
    container_name: mean-server
    ports:
      - '3000:5200'
    depends_on:
      - mongodb
    environment:
      ATLAS_URI: mongodb://test:test@mongodb:27017/meanStackExample?retryWrites=true&w=majority 