services:
  # mean-server:
  #   image: server:mean-ex # Sử dụng image đã build sẵn cho mean-server
  #   container_name: mean-server
  #   ports:
  #     - "3030:3030"
  #   networks:
  #     - mean-network
  #   environment:
  #     DB_HOST: mysql
  #     DB_USER: d3v
  #     DB_PASSWORD: devops2024
  #     DB_NAME: note_app
  #     DB_PORT: 33066
  #   depends_on:
  #     - mysql

  mean-client:
    image: client:mean-ex # Sử dụng image đã build sẵn cho mean-client
    container_name: mean-client
    ports:
      - "4200:80"
    networks:
      - mean-network

  mysql:
    image: mysql:5.7 # Sử dụng MySQL 5.7
    container_name: mysql
    ports:
      - "33066:33066"
    networks:
      - mean-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Mật khẩu root để quản trị
      MYSQL_DATABASE: note_app # Tạo cơ sở dữ liệu ban đầu
      MYSQL_USER: d3v # Tạo user tùy chỉnh
      MYSQL_PASSWORD: devops2024 # Mật khẩu cho user tùy chỉnh
      MYSQL_TCP_PORT: 33066

networks:
  mean-network:
    driver: bridge
